apiVersion: v1
kind: Service
metadata:
  name: driver-service
  labels:
    app: driver-service
spec:
  type: NodePort
  selector:
    app: driver-service
  ports:
  - protocol: TCP
    port: 8000        # Port exposed within the cluster
    targetPort: 8000  # Port on the pod
    nodePort: 30080   # Port accessible from host (30000-32767 range)

